/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DealerEnquiryRouteImport } from './routes/dealer-enquiry'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard_.orders'
import { Route as DashboardQuotationsRouteImport } from './routes/dashboard_.quotations'
import { Route as DashboardTicketsRouteImport } from './routes/dashboard_.tickets'
import { Route as DashboardWishlistRouteImport } from './routes/dashboard_.wishlist'
import { Route as ProductsSlugRouteImport } from './routes/products_.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DealerEnquiryRoute = DealerEnquiryRouteImport.update({
  id: '/dealer-enquiry',
  path: '/dealer-enquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/dashboard_/orders',
  path: '/dashboard/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardQuotationsRoute = DashboardQuotationsRouteImport.update({
  id: '/dashboard_/quotations',
  path: '/dashboard/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTicketsRoute = DashboardTicketsRouteImport.update({
  id: '/dashboard_/tickets',
  path: '/dashboard/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWishlistRoute = DashboardWishlistRouteImport.update({
  id: '/dashboard_/wishlist',
  path: '/dashboard/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products_/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/dealer-enquiry': typeof DealerEnquiryRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/order-success': typeof OrderSuccessRoute
  '/products': typeof ProductsRoute
  '/register': typeof RegisterRoute
  '/track-order': typeof TrackOrderRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/quotations': typeof DashboardQuotationsRoute
  '/dashboard/tickets': typeof DashboardTicketsRoute
  '/dashboard/wishlist': typeof DashboardWishlistRoute
  '/products/$slug': typeof ProductsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/dealer-enquiry': typeof DealerEnquiryRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/order-success': typeof OrderSuccessRoute
  '/products': typeof ProductsRoute
  '/register': typeof RegisterRoute
  '/track-order': typeof TrackOrderRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/quotations': typeof DashboardQuotationsRoute
  '/dashboard/tickets': typeof DashboardTicketsRoute
  '/dashboard/wishlist': typeof DashboardWishlistRoute
  '/products/$slug': typeof ProductsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/dealer-enquiry': typeof DealerEnquiryRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/order-success': typeof OrderSuccessRoute
  '/products': typeof ProductsRoute
  '/register': typeof RegisterRoute
  '/track-order': typeof TrackOrderRoute
  '/dashboard_/orders': typeof DashboardOrdersRoute
  '/dashboard_/quotations': typeof DashboardQuotationsRoute
  '/dashboard_/tickets': typeof DashboardTicketsRoute
  '/dashboard_/wishlist': typeof DashboardWishlistRoute
  '/products_/$slug': typeof ProductsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/dealer-enquiry'
    | '/events'
    | '/forgot-password'
    | '/gallery'
    | '/login'
    | '/offers'
    | '/order-success'
    | '/products'
    | '/register'
    | '/track-order'
    | '/dashboard/orders'
    | '/dashboard/quotations'
    | '/dashboard/tickets'
    | '/dashboard/wishlist'
    | '/products/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/dealer-enquiry'
    | '/events'
    | '/forgot-password'
    | '/gallery'
    | '/login'
    | '/offers'
    | '/order-success'
    | '/products'
    | '/register'
    | '/track-order'
    | '/dashboard/orders'
    | '/dashboard/quotations'
    | '/dashboard/tickets'
    | '/dashboard/wishlist'
    | '/products/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/dealer-enquiry'
    | '/events'
    | '/forgot-password'
    | '/gallery'
    | '/login'
    | '/offers'
    | '/order-success'
    | '/products'
    | '/register'
    | '/track-order'
    | '/dashboard_/orders'
    | '/dashboard_/quotations'
    | '/dashboard_/tickets'
    | '/dashboard_/wishlist'
    | '/products_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BlogRoute: typeof BlogRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DealerEnquiryRoute: typeof DealerEnquiryRoute
  EventsRoute: typeof EventsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  OffersRoute: typeof OffersRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  ProductsRoute: typeof ProductsRoute
  RegisterRoute: typeof RegisterRoute
  TrackOrderRoute: typeof TrackOrderRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardQuotationsRoute: typeof DashboardQuotationsRoute
  DashboardTicketsRoute: typeof DashboardTicketsRoute
  DashboardWishlistRoute: typeof DashboardWishlistRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealer-enquiry': {
      id: '/dealer-enquiry'
      path: '/dealer-enquiry'
      fullPath: '/dealer-enquiry'
      preLoaderRoute: typeof DealerEnquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/orders': {
      id: '/dashboard_/orders'
      path: '/dashboard/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/quotations': {
      id: '/dashboard_/quotations'
      path: '/dashboard/quotations'
      fullPath: '/dashboard/quotations'
      preLoaderRoute: typeof DashboardQuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/tickets': {
      id: '/dashboard_/tickets'
      path: '/dashboard/tickets'
      fullPath: '/dashboard/tickets'
      preLoaderRoute: typeof DashboardTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/wishlist': {
      id: '/dashboard_/wishlist'
      path: '/dashboard/wishlist'
      fullPath: '/dashboard/wishlist'
      preLoaderRoute: typeof DashboardWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/$slug': {
      id: '/products_/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BlogRoute: BlogRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DealerEnquiryRoute: DealerEnquiryRoute,
  EventsRoute: EventsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  OffersRoute: OffersRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  ProductsRoute: ProductsRoute,
  RegisterRoute: RegisterRoute,
  TrackOrderRoute: TrackOrderRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardQuotationsRoute: DashboardQuotationsRoute,
  DashboardTicketsRoute: DashboardTicketsRoute,
  DashboardWishlistRoute: DashboardWishlistRoute,
  ProductsSlugRoute: ProductsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
